databaseChangeLog:
    - logicalFilePath: path_independent
    - include:
        file: database/seeds/seed.yaml
    - include:
        file: database/datasets/seed-data.yaml
    - include:
        file: database/datasets/test-data.yaml
    - include:
        file: database/changes/0001.create_table_notifications.yaml
    - include:
        file: database/changes/0002.create_table_subscriptions.yaml
    - include:
        file: database/changes/0003.create_table_channels.yaml
    - include:
        file: database/changes/0004.create_table_message_templates.yaml
    - include:
        file: database/changes/0005.create_table_message_template_translatables.yaml      
    - include:
        file: database/changes/0006.create_table_message_definitions.yaml
    - include:
        file: database/changes/0007.create_table_visitors.yaml
    - include:
        file: database/changes/0008.create_table_addresses.yaml
    - include:
        file: database/changes/0009.create_table_contacts.yaml
    - include:
        file: database/changes/0010.create_table_social_media.yaml
    - include:
        file: database/changes/0011.create_table_pages.yaml
    - include:
        file: database/changes/0012.create_table_page_visitors.yaml
    - include:
        file: database/changes/0013.create_table_page_translatables.yaml
    - include:
        file: database/changes/0014.create_table_menues.yaml
    - include:
        file: database/changes/0015.create_table_menu_translatables.yaml
    - include:
        file: database/changes/0016.create_table_features.yaml
    - include:
        file: database/changes/0017.migrate_data_features.yaml
    - include:
        file: database/changes/0018.rename_pages_and_translatables.yaml
    - include:
        file: database/changes/0019.create_table_menu_items.yaml
    - include:
        file: database/changes/0020.create_table_menu_item_translatables.yaml
    - include:
        file: database/changes/0020.create_table_feature_translatables.yaml
    - include:
        file: database/changes/0021.create_table_landing_features.yaml
    - include:
        file: database/changes/0022.create_table_user_contexts.yaml
    - include:
        file: database/changes/0023.create_table_event_categories.yaml
    - include:
        file: database/changes/0024.create_table_event_category_translatables.yaml
    - include:
        file: database/changes/0025.create_table_event_target_groups.yaml
    - include:
        file: database/changes/0026.create_table_target_group_translatables.yaml
    - include:
        file: database/changes/0027.create_table_attendee_configurations.yaml
    - include:
        file: database/changes/0028.create_table_events.yaml
    - include:
        file: database/changes/0029.add_column_favorite_events.yaml
    - include:
        file: database/changes/0030.create_table_schedules.yaml
    - include:
        file: database/changes/0031.create_table_event_translatables.yaml
    - include:
        file: database/changes/0032.create_table_attendees.yaml
    - include:
        file: database/changes/0033.create_table_event_visitors.yaml
    - include:
        file: database/changes/0034.create_table_public_authors.yaml
    - include:
        file: database/changes/0035.create_table_article_categories.yaml
    - include:
        file: database/changes/0036.create_table_article_category_translatables.yaml
    - include:
        file: database/changes/0037.create_table_articles.yaml
    - include:
        file: database/changes/0038.create_table_article_visitors.yaml
    - include:
        file: database/changes/0039.create_table_article_translatables.yaml
    - include:
        file: database/changes/0040.create_table_article_ratings.yaml
    - include:
        file: database/changes/0041.create_table_article_comments.yaml
    - include:
        file: database/changes/0042.create_table_article_comment_translatables.yaml
    - include:
        file: database/changes/0043.create_table_contest_types.yaml
    - include:
        file: database/changes/0044.create_table_contest_states.yaml
    - include:
        file: database/changes/0045.create_table_contests.yaml
    - include:
        file: database/changes/0046.create_table_contest_type_translatables.yaml
    - include:
        file: database/changes/0047.create_table_contest_translatables.yaml
    - include:
        file: database/changes/0048.create_table_contest_participations.yaml
    - include:
        file: database/changes/0049.create_table_contest_participation_translatables.yaml
    - include:
        file: database/changes/0050.create_table_contest_votes.yaml
    - include:
        file: database/changes/0051.create_table_form_template_types.yaml 
    - include:
        file: database/changes/0052.create_table_form_templates.yaml
    - include:
        file: database/changes/0053.create_table_user_form_templates.yaml
    - include:
        file: database/changes/0055.create_table_form_template_type_translatables.yaml
    - include:
        file: database/changes/0056.create_table_form_template_translatables.yaml
    - include:
        file: database/changes/0057.create_table_deal_categories.yaml
    - include:
        file: database/changes/0058.create_table_deal_category_translatables.yaml
    - include:
        file: database/changes/0059.create_table_deals.yaml
    - include:
        file: database/changes/0060.create_table_deal_translatables.yaml
    - include:
        file: database/changes/0061.create_table_deal_visitors.yaml 
    - include:
        file: database/changes/0062.add_column_favorite_deals.yaml
    - include:
        file: database/changes/0063.create_table_organisations.yaml
    - include:
        file: database/changes/0064.add_column_favorite_organisations.yaml
    - include:
        file: database/changes/0065.add_column_organisation_to_events.yaml
    - include:
        file: database/changes/0066.create_table_organisation_visitors.yaml
    - include:
        file: database/changes/0067.create_table_members.yaml
    - include:
        file: database/changes/0068.create_table_organisation_ratings.yaml
    - include:
        file: database/changes/0069.create_table_organisation_comments.yaml
    - include:
        file: database/changes/0070.create_table_organisation_comment_translatables.yaml
    - include:
        file: database/changes/0071.create_table_survey_states.yaml
    - include:
        file: database/changes/0072.create_table_surveys.yaml
    - include:
        file: database/changes/0073.create_table_survey_visitors.yaml
    - include:
        file: database/changes/0074.create_table_assignments.yaml
    - include:
        file: database/changes/0075.create_table_question_types.yaml
    - include:
        file: database/changes/0076.create_table_questions.yaml
    - include:
        file: database/changes/0077.create_table_survey_results.yaml
    - include:
        file: database/changes/0078.create_table_question_options.yaml
    - include:
        file: database/changes/0079.create_table_answers.yaml
    - include:
        file: database/changes/0080.create_table_answer_translatables.yaml   
    - include:
        file: database/changes/0081.create_table_survey_translatables.yaml   
    - include:
        file: database/changes/0082.create_table_survey_result_translatables.yaml
    - include:
        file: database/changes/0083.create_table_question_translatables.yaml   
    - include:
        file: database/changes/0084.create_table_question_option_translatables.yaml
    - include:
        file: database/changes/0085.create_table_theme_variables.yaml  
    - include:
        file: database/changes/0086.drop_tables.yaml      
    - include:
        file: database/changes/0089.create_table_verifications.yaml   
    - include:
        file: database/changes/0090.create_table_password_resets.yaml
    - include:
        file: database/changes/0091.create_table_inquiry_category.yaml
    - include:
        file: database/changes/0092.create_table_inquiry.yaml
    - include:
        file: database/changes/0093.create_table_inquiry_category_translatables.yaml
    - include:
        file: database/changes/0094.create_table_error_messages.yaml
    - include:
        file: database/changes/0095.add_data_menu_items.yaml
    - include:
        file: database/changes/0096.migrate_cleanUp.yaml
    - include:
        file: database/changes/0097.create_table_app_stores.yaml