databaseChangeLog:
  - logicalFilePath: path_independent

  - changeSet:
      id: 0006.test-data.1
      author: codeschluss
      changes:
        - sql:
            comment: Update captcha sitekey to test key
            splitStatements: true
            sql: update configurations
                 set value = '10000000-ffff-ffff-ffff-000000000001'
                 where `key` = 'hCaptchaSitekey';
                 
  - changeSet:
      id: 0006.test-data.2
      author: codeschluss
      changes:
        - sql:
            comment: Add configurations
            splitStatements: true
            sql:
               insert into configurations (`id`, `key`, `value`, `media_id`) values
               ('701de29d-0170-48fa-aa71-12e899500de6', 'logo', null, '3e791600-8e00-4069-a060-4862c44da93b'),
               ('458f85bb-ee49-44fa-8bc8-538b52c7b5e4', 'logoText', null, '6c92cfcd-d65d-47d9-bdc5-b8004afe916c'),
               ('0ad29ce1-a519-417c-91c5-28a346185542', 'favicon', null, 'fc8a64b5-7335-4309-a5c1-e9d2de53c338'),
               ('f53a4515-cbe2-450e-89ac-d9392d3f88c3', 'guestArticleSuccess', null, 'd84b7e0b-7ff2-4001-8a0a-337852999733');