databaseChangeLog:
  - logicalFilePath: path_independent
  - changeSet:
      id: 0027.create_table_attendee_configurations.1
      author: codeschluss
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: attendee_configurations_primary_key
                  name: id
                  type: CHAR(36)
              - column:
                  constraints:
                    nullable: false
                  defaultValueComputed: CURRENT_TIMESTAMP
                  name: created
                  type: TIMESTAMP WITH TIME ZONE
              - column:
                  constraints:
                    nullable: false
                  defaultValueComputed: CURRENT_TIMESTAMP
                  name: modified
                  type: TIMESTAMP WITH TIME ZONE
              - column:
                  constraints:
                    nullable: false
                  name: max_attendees
                  type: INTEGER
              - column:
                  constraints:
                    nullable: false
                  defaultValueBoolean: false
                  name: approval
                  type: boolean                                                                
            tableName: attendee_configurations                       
          
            