databaseChangeLog:
  - logicalFilePath: path_independent
  - changeSet:
      id: 0027.create_table_event_attendee_configurations.1
      author: codeschluss
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: event_attendee_configurations_primary_key
                  name: id
                  type: CHAR(36)
              - column:
                  constraints:
                    nullable: false
                  defaultValueComputed: CURRENT_TIMESTAMP
                  name: created
                  type: datetime
              - column:
                  constraints:
                    nullable: false
                  defaultValueComputed: CURRENT_TIMESTAMP
                  name: modified
                  type: datetime
              - column:
                  name: max_attendees
                  type: INTEGER
              - column:
                  constraints:
                    nullable: false
                  defaultValueBoolean: false
                  name: approval
                  type: boolean                                                                
            tableName: event_attendee_configurations 
        - sql:
            comment: set char set for mysql
            dbms: mysql
            endDelimiter: \nGO
            splitStatements: true
            sql: ALTER TABLE event_attendee_configurations CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
            
            