databaseChangeLog:
  - logicalFilePath: path_independent
  - changeSet:
      id: 0107.add_column_configurations_media.1
      author: codeschluss
      changes:
        - addColumn:
            columns:
              - column:
                  name: media_id
                  type: CHAR(36)
            tableName: configurations
  - changeSet:
      id: 0107.add_column_configurations_media.2
      author: codeschluss
      changes:
        - createIndex:
            columns:
              - column:
                  name: media_id
            indexName: idx_fk_configurations_media_id
            tableName: configurations
  - changeSet:
      id: 0107.add_column_configurations_media.3
      author: codeschluss
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: media_id
            baseTableName: configurations
            constraintName: fk_configurations_media_id
            deferrable: false
            initiallyDeferred: false
            onUpdate: CASCADE
            referencedColumnNames: id
            referencedTableName: media
            validate: true
  - changeSet:
      id: 0107.add_column_configurations_media.4
      author: codeschluss
      changes:
        - dropNotNullConstraint:
            columnDataType: varchar(255)
            columnName: value
            tableName: configurations
  - changeSet:
      id: 0107.add_column_configurations_media.5
      author: codeschluss
      changes:
        - dropNotNullConstraint:
            columnDataType: mediumblob
            columnName: image
            tableName: media
            