databaseChangeLog:
  - logicalFilePath: path_independent
  - changeSet:
      id: 0128.create_table_role_applications.1
      author: codeschluss
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: role_applications_primary_key
                  name: id
                  type: CHAR(36)
              - column:
                  constraints:
                    nullable: false
                  defaultValueComputed: CURRENT_TIMESTAMP
                  name: created
                  type: datetime
              - column:
                  constraints:
                    nullable: false
                  defaultValueComputed: CURRENT_TIMESTAMP
                  name: modified
                  type: datetime
              - column:
                  constraints:
                    nullable: false
                  defaultValueBoolean: false
                  name: accepted
                  type: boolean      
              - column:
                  constraints:
                    nullable: false
                  name: user_id
                  type: CHAR(36) 
              - column:
                  constraints:
                    nullable: false
                  name: role_id
                  type: CHAR(36)                                                 
            tableName: role_applications
        - sql:
            comment: set char set for mysql
            dbms: mysql
            endDelimiter: \nGO
            splitStatements: true
            sql: ALTER TABLE role_applications CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;  
            
  - changeSet:
      id: 0128.create_table_role_applications.2
      author: codeschluss
      changes:
        - createIndex:
            columns:
              - column:
                  name: user_id
            indexName: idx_fkoa4vzd4mzr6mvt4vh4o0drftk
            tableName: role_applications
  - changeSet:
      id: 0128.create_table_role_applications.3
      author: codeschluss
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: user_id
            baseTableName: role_applications
            constraintName: fkoa4vzd4mzr6mvt4vh4o0drftk
            deferrable: false
            initiallyDeferred: false
            onUpdate: CASCADE
            onDelete: CASCADE
            referencedColumnNames: id
            referencedTableName: users
            validate: true   
            
  - changeSet:
      id: 0128.create_table_role_applications.4
      author: codeschluss
      changes:
        - createIndex:
            columns:
              - column:
                  name: role_id
            indexName: idx_fk8epiuule5ldv210fhiz4h76u5
            tableName: role_applications
  - changeSet:
      id: 0128.create_table_role_applications.5
      author: codeschluss
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: role_id
            baseTableName: role_applications
            constraintName: fk8epiuule5ldv210fhiz4h76u5
            deferrable: false
            initiallyDeferred: false
            onUpdate: CASCADE
            onDelete: CASCADE
            referencedColumnNames: id
            referencedTableName: roles
            validate: true                         
                                  
