databaseChangeLog:
  - logicalFilePath: path_independent
  - changeSet:
      id: 0131.create_table_privilege_application_translatables.1
      author: codeschluss
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: privilege_application_translatables_primary_key
                  name: id
                  type: CHAR(36)
              - column:
                  constraints:
                    nullable: false
                  defaultValueComputed: CURRENT_TIMESTAMP
                  name: created
                  type: datetime
              - column:
                  constraints:
                    nullable: false
                  defaultValueComputed: CURRENT_TIMESTAMP
                  name: modified
                  type: datetime
              - column:
                  name: content
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: parent_id
                  type: CHAR(36)         
              - column:
                  constraints:
                    nullable: false
                  name: language_id
                  type: CHAR(36)                                                                               
            tableName: privilege_application_translatables
        - sql:
            comment: set char set for mysql
            dbms: mysql
            endDelimiter: \nGO
            splitStatements: true
            sql: ALTER TABLE privilege_application_translatables CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;              

  - changeSet:
      id: 0131.create_table_privilege_application_translatables.2
      author: codeschluss
      changes:
        - createIndex:
            columns:
              - column:
                  name: parent_id
            indexName: idx_fkgtiicqvxooi7ppq0opc0qg16e
            tableName: privilege_application_translatables
  - changeSet:
      id: 0131.create_table_privilege_application_translatables.3
      author: codeschluss
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: parent_id
            baseTableName: privilege_application_translatables
            constraintName: fkgtiicqvxooi7ppq0opc0qg16e
            deferrable: false
            initiallyDeferred: false
            onUpdate: CASCADE
            onDelete: CASCADE
            referencedColumnNames: id
            referencedTableName: privilege_applications
            validate: true   
            
  - changeSet:
      id: 0131.create_table_privilege_application_translatables.4
      author: codeschluss
      changes:
        - createIndex:
            columns:
              - column:
                  name: language_id
            indexName: idx_fk20ihm83smk6ji9imxfm5ojg3m
            tableName: privilege_application_translatables
  - changeSet:
      id: 0131.create_table_privilege_application_translatables.5
      author: codeschluss
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: language_id
            baseTableName: privilege_application_translatables
            constraintName: fk20ihm83smk6ji9imxfm5ojg3m
            deferrable: false
            initiallyDeferred: false
            onUpdate: CASCADE
            onDelete: CASCADE
            referencedColumnNames: id
            referencedTableName: languages
            validate: true
            
               

                     
            